include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
    inference_failure_on_function_invocation: ignore
    inference_failure_on_untyped_parameter: ignore
    unused_import: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"
    - "**/build/**"
    - "**/.dart_tool/**"
    - "**/ios/Pods/**"
    - "**/android/.gradle/**"
    - "**/android/app/build/**"
    - "**/android/build/**"
    - "**/web/**"
    - "**/test/**"
  strong-mode:
    implicit-casts: true
    implicit-dynamic: false

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - avoid_print
    - prefer_single_quotes
    - avoid_unnecessary_containers
    - prefer_const_constructors_in_immutables
    - prefer_final_locals
    - prefer_if_elements_to_conditional_expressions
    - prefer_null_aware_operators
    - sort_child_properties_last
    - use_build_context_synchronously
    - use_key_in_widget_constructors
    - use_super_parameters
    - avoid_web_libraries_in_flutter
