workflows:
  ios-ipa-build:
    name: iOS IPA Build
    max_build_duration: 120
    environment:
      flutter: 3.29.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get

      - name: iOS Pod install
        script: |
          cd ios && pod install --repo-update

      - name: Build iOS IPA
        script: |
          flutter build ipa --release \
            --export-options-plist ios/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa

  android-build:
    name: Android APK Build
    max_build_duration: 60
    environment:
      flutter: 3.29.0
      android-sdk: latest
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get

      - name: Build Android APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/*.apk

  web-build:
    name: Web Build
    max_build_duration: 60
    environment:
      flutter: 3.29.0
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get

      - name: Build Web
        script: |
          flutter build web --release

    artifacts:
      - build/web/**/*
