name: Build Web

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-web:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: false

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.0'
        channel: 'stable'

    - name: Cleanup old artifacts
      if: github.event_name == 'workflow_dispatch'
      continue-on-error: true
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh api /repos/${{ github.repository }}/actions/artifacts --paginate --jq '.artifacts[] | select(.expired == false) | .id' | while read id; do
          gh api -X DELETE /repos/${{ github.repository }}/actions/artifacts/$id
        done

    - name: Get dependencies
      run: flutter pub get

    - name: Build Web
      run: flutter build web --release

    - name: Upload Web Build
      if: success() && github.event_name == 'workflow_dispatch'
      continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: quotify-web
        path: build/web/**/*
        retention-days: 1